<h3 style = "color:white"><b>AQUÍ EMPEZARÁN LOS ARRAYS</b></h3>

In [21]:
import numpy as np

<h3 style = "color:white"><b>Haciendo listas</b></h3>

In [22]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

<h3 style = "color:white"><b>Transformando la lista a arrays</b></h3>

In [23]:
arreglo= np.array(numbers)

In [24]:
type(numbers)

list

<h3 style = "color:white"><b>Mide la cantidad de bits en el array</b></h3>

In [25]:
arreglo.dtype

dtype('int32')

<h3 style = "color:white"><b>Definiendo el arreglo de INT a FLOAT</b></h3>

In [26]:
np.array(arreglo, dtype=np.float32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

<h3 style = "color:white"><b>Transformando los datos existentes a flotantes</b></h3>

In [27]:
arreglo.astype(np.float32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)


<h3 style = "color:white"><b>Un range adaptado a un array, no funciona el range común</b></h3>

In [28]:
new_array = np.arange(1,11)
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3 style = "color:white"><b>Un arange pero de 2 en 2</b></h3>

In [29]:
new_array2 = np.arange (1,11,2)
new_array2

array([1, 3, 5, 7, 9])

<h3 style = "color:white"><b>Sacando el promedio del arreglo</b></h3>

In [30]:
promedy = np.mean(new_array)
promedy

5.5

<h3 style = "color:white"><b>Sacando la mediana del arreglo</b></h3>

In [31]:
median = np.median(new_array)
median

5.5

<h3 style = "color:white"><b>Rellenando el arreglo con unos</b></h3>

In [32]:
array_ones = np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h3 style = "color:white"><b>Pasando el array de flotantes a enteros</b></h3>

In [33]:
array_int_ones = array_ones.astype(int)
array_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:white"><b>Un array de ceros</b></h3>

In [34]:
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<h3 style = "color:white"><b>Ahora como el del uno, pasemos este array de ceros de flotantes a enteros</b></h3>

In [35]:
array_int_zeros = array_zeros.astype(int)
array_int_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<h3 style = "color:white"><b>Un array de números randoms</b></h3>

In [36]:
ram_array = np.random.rand(5)
ram_array

array([0.36087741, 0.14406251, 0.46756299, 0.99606663, 0.27667811])

<h3 style = "color:white"><b>Ahora generemos una matriz de 3x3. El array anterior era de un vector de una dimensión</b></h3>

In [37]:
matriz = np.random.rand(3,3)
matriz

array([[0.23773376, 0.53609513, 0.87244485],
       [0.50635847, 0.56734018, 0.80987755],
       [0.79305077, 0.19687123, 0.54245412]])

<h3 style = "color:white"><b>Ahora un arreglo aleatorios de 10 números enteros del 1 al 5</b></h3>

In [38]:
ram_array2 = np.random.randint(1,5,10)
ram_array2

array([1, 3, 1, 4, 3, 3, 3, 4, 1, 3])

<h3 style = "color:white"><b>Generando una matriz aleatoria de 10 números enteros del 1 al 100</b></h3>

In [39]:
matriz2 = np.random.randint(1,100,(5,5))
matriz2

array([[41, 89, 86, 82, 92],
       [34, 71, 69,  1, 36],
       [50, 91, 23, 40, 26],
       [84, 90, 97, 67,  9],
       [45, 10, 56, 78, 21]])